on:
  pull_request:
    branches: [ source ]
  push:
    branches: [ source ]

name: Deploy to GitHub Pages

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository and submodules
      uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
    - name: Install dependencies
      run: uv sync --locked
    - name: Build site
      run: uv run pelican content --settings publishconf.py
    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@v5
      with:
        path: output/
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/source'
    needs: [ build ]
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: https://blog.jonrshar.pe/
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v5
