on: push

name: Deploy to GitHub pages

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        cache: 'pip'
        python-version: '3.12'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Build site
      run: pelican content --settings publishconf.py
    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: output/
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/source'
    needs: [ build ]
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: https://blog.jonrshar.pe/
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
