on: push
name: Deploy to GitHub pages
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Publish to GitHub Pages
      uses: nelsonjchen/gh-pages-pelican-action@0.1.4
      env:
        GH_PAGES_BRANCH: master
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        PELICAN_CONFIG_FILE: publishconf.py
