on: push
name: Deploy to GitHub pages
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Publish to GitHub Pages
      uses: nelsonjchen/gh-pages-pelican-action@0.1.4
      env:
        GH_PAGES_BRANCH: master
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        PELICAN_CONFIG_FILE: publishconf.py
